version: '3.9'
services:
  discord-bot:
    build:
      context: .
      dockerfile: container/Dockerfile
    volumes:
      - .:/app
    network_mode: "bridge"
    env_file:
      - .env
    restart: unless-stopped